### ISSUE TITLE
Capacities class - why not allow initialization of fields within constructor?

### ISSUE THREAD

**Issue by nannkat** [fabric-testbed/InformationModel#51]
Seems a bit complex to have to set_fields() manually though its good to have the option. 

<img width="794" alt="cap" src="https://user-images.githubusercontent.com/54936808/120015373-44d72880-bfb1-11eb-9130-6ee4ad7de42c.png">

Would be intuitive to be able to have it a one-liner: 
<img width="924" alt="cap2" src="https://user-images.githubusercontent.com/54936808/120015816-cc249c00-bfb1-11eb-87fa-f68be49c6486.png">

**Comment by paul-ruth** [comment]
What user functionality does exposing the Capacities object to the user enable that is not possible otherwise? I can not imagine a use other than setting/getting value.

If there is no additional user functionality, then this object should remain hidden from the user and the API should be node1.set_properties(core=4, ram=32, disk=200, image_type='qcow2', image_ref='default_ubuntu_20')

Probably, image_type is necessary too.  Shouldn't the image_ref string refer to an object that knows what type it is?

**Comment by ibaldin** [comment]
User has access to capacities and allocated_capacities object. Same fields, different meaning. One is what is being requested, the other is what is being provided. You ask for capacities.(core=1, ram=2), you get allocated_capacities(core=1, ram=10), but the capacities field preserves what you asked for.

**Comment by paul-ruth** [comment]
I think having the two different object helps you store that information but doesn't help the user access them. They don't add any functionality for the user but they do add complexity in that the user needs to understand data structures that should be encapsulated in the node object.  

I think this either needs to be:

my_node.set_properties(core=4, ram=32, disk=200, image_type='qcow2', image_ref='default_ubuntu_20')

Then my_node.get_properties returns a dict of all the properties with the requested properties recorded and labeled as "requested_properties" .   Then 99% of the users will set core/ram/disk and get (maybe) slightly more than that. They can use the API without knowing anything about the underlying objects. If they want to know the actual requested values they they can look but most users will just get/set as if they were the same.  In general, I think "capacities" should be what "is" and "requested capacities" should be what was requested. 

Alternatively, instance type and image can to be first order objects like:

my_instance_type = fim.get_instance_type(core=4, ram=32, disk=200)
my_image = fim.get_image(image_type='qcow2', image_ref='default_ubuntu_20')
my_node1.set_properties(instance_type=my_instance_type, image = my_image)

In this case, the the user will always request a valid instance type and valid image because it comes from the list of valid ones.  Maybe there is an optional parameter that defaults to 'true' and makes  fim.get_instance_type round up the instance_type an exact match is not found.  If set to 'false' it will error if no exact match is found.   I essence, this is what AWS and all the other do which is to require the user choose and exact instance type and image but our API can help them make choices easier.  

I think part of the problem here is that this is trying to allow the AMs or SM to "round" the requests. I think the rounding should be done by the user (with help from the API) before the SM gets the request.  This way there is never a difference between what is requested and what is allocated or at least the user knows the difference before they make the request and storing and managing that information is not necessary (for the system or the user).   In both cases above the API can do the "rounding".  Even in the first case you should be able to "get_properties" and know what you are going to get before you make the request.

**Comment by ibaldin** [comment]
I will keep this issue open. I don't think I fully agree with what you are saying, but I also don't necessarily completely like the way it is either. The difference between what was asked and what was allocated can be important, but you may be right that this is not the job of the CF Orchestrator to decide, but rather the tools. So the end result (which is what I care about) is that the user can know  the difference between what they want (they may have programmatically determined the dimensions of their VM) and what they will get.

**Comment by ibaldin** [comment]
I believe this has been dealt with at this point through a combination of changes in rel-1.1 branch and FABlib adaptations.
